### ISSUE TITLE
Inquiry regarding [GEC] Master Edition 1.9.1 PSX DOOM.

### ISSUE THREAD

**Issue by Acts19quiz** [Erick194/PSXDOOM-RE#3]
This isn't a PSXDOOM issue per se, but rather I need some information regarding the licensing state of your (and Gerardo194's) [GEC] Master Edition 1.9.1 port with regards to copying specific portions of the code into a GZDoom fork of mine.

@Erick194 If you're the right person I'm looking for and would like to follow up on this question in private, you can just send an email to the G-mail address of my github account name (obviously not posting it outright due to spambots). Sorry if this is a bit convoluted, but I didn't know how else to get a hold of you on github. Thank you for your time.

**Comment by Erick194** [comment]
Hello greetings, here I leave you my email
erickv5394@gmail.com
